### ISSUE TITLE
Not work in android 5.0.2

### ISSUE THREAD

**Issue by Danyzzz** [MangoTools/cordova-plugin-lightSensor#1]
I tried this plugin with example 1 but it seems not working...

**Comment by Danyzzz** [comment]
I'm sorry, worked perfetly!

**Comment by Elvincth** [comment]
How do u get it work?

**Comment by Danyzzz** [comment]
Hi!
put this into your page:

<!DOCTYPE html>
<html>
  <head>
    <title>Device Ready Example</title>

```
<script type="text/javascript" charset="utf-8" src="cordova.js"></script>
<script type="text/javascript" charset="utf-8">

// Wait for device API libraries to load
//
function onLoad() {
    document.addEventListener("deviceready", onDeviceReady, false);
}

// device APIs are available
//
function onDeviceReady() {
  window.light = cordova.require("cordova-plugin-lightSensor.light");
}
```

function onSuccess(state) {
        alert('Light Sensor state: ' + state);
  }

navigator.proximity.enableSensor();

  setInterval(function() {
       window.light.getLightState(onSuccess);
  }, 1000);
    </script>
  </head>
  <body onload="onLoad()">
  </body>
</html>

Enjoy!

**Comment by Elvincth** [comment]
Just ried it really work thx!

**Comment by jean-baptiste-blanc** [comment]
No longer relevent
